"""Filesystem contract.

Inputs live under one data root, set with the ``EEG_DATA_ROOT`` environment variable (default
``./data``):

    <EEG_DATA_ROOT>/datasets/     the raw releases, as downloaded (see README)
    <EEG_DATA_ROOT>/harmonised/   the cleaned cache written by experiments/h00_harmonise.py:
                                  one ``.npy`` per recording (19 channels, 256 Hz, float32,
                                  unscaled volts) plus a ``.json`` sidecar with the channel list,
                                  diagnostic group and QC record

Everything the analysis writes lands under ``./outputs``.
"""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DATA_ROOT = Path(os.environ.get("EEG_DATA_ROOT", ROOT / "data"))
#: Kept under its historical name; the experiments refer to it.
SOURCE_ROOT = DATA_ROOT

HARMONISED = DATA_ROOT / "harmonised"
DATASETS = DATA_ROOT / "datasets"

#: Arms generated by ``experiments/e09_extend_corpus.py``.
HARMONISED_EXTRA = ROOT / "outputs" / "harmonised_extra"
HARMONISED_NOICA = ROOT / "outputs" / "harmonised_noica"

CAUEEG_ANNOTATION = DATASETS / "caueeg-dataset" / "annotation.json"
DS004504_PARTICIPANTS = DATASETS / "openneuro_ds004504_raw" / "participants.tsv"
MISP_STATES = [DATASETS / "MISP" / "set1" / "states.xlsx", DATASETS / "MISP" / "set2" / "States.xlsx"]

OUT = ROOT / "outputs"
RESULTS = OUT / "results"
FIGURES = OUT / "figures"
LOGS = OUT / "logs"
CACHE = OUT / "cache"

SPINE = CACHE / "spine.csv"
WINDOW_CACHE = CACHE / "windows.npz"


def ensure_dirs() -> None:
    for d in (OUT, RESULTS, FIGURES, LOGS, CACHE):
        d.mkdir(parents=True, exist_ok=True)


def require_source() -> None:
    """Fail loudly and early rather than half-way through a sweep."""
    if not HARMONISED.is_dir() or not any(HARMONISED.glob("*.npy")):
        raise SystemExit(
            f"harmonised cache not found or empty at {HARMONISED}\n"
            f"set EEG_DATA_ROOT to a directory holding datasets/ and run\n"
            f"    python experiments/h00_harmonise.py"
        )
